version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      patterns:
        - "*"
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
