name: 'Conda dependency submission action'
description: 'Upload information about your Anaconda environment to the GitHub dependency graph'
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Actions runner."
    required: false
    default: ${{ github.token }}
  filePath:  
    description: 'The path to the directory containing the environment files to upload. Defaults to Actions working directory.'
    required: false
    default: '.'
  filePattern:
    description: 'The file name pattern for environment files to upload'
    required: false
    default: 'environment.yaml'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'blue'
