name: "Test"
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        npm install
        node --experimental-vm-modules node_modules/jest/bin/jest.js
        
